FROM node:10 AS builder

# working directory
RUN mkdir -p /opt/app && \
    chown node /opt/app
WORKDIR /opt/app
USER node

# cache node_modules
COPY --chown=node package.json yarn.lock /opt/app/
RUN yarn install --frozen-lockfile --non-interactive && \
    yarn cache clean

# do the build
COPY --chown=node . /opt/app/
RUN yarn run test && \
    yarn run build

# ------------------------------------------------------------

FROM nginx:1.14-alpine

COPY etc/web/nginx-default.conf /etc/nginx/conf.d/default.conf

COPY src/main/web /usr/share/nginx/html
COPY --from=builder /opt/app/target/webpack /usr/share/nginx/html
