version: '2'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: luontola/cqrs-hotel-web
    ports:
    - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: luontola/cqrs-hotel-api
    environment:
      DB_USERNAME: cqrshotel
      DB_PASSWORD: cqrshotel
      DB_URL: jdbc:postgresql://db:5432/cqrshotel
    ports:
    - "8081:8080"

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_USER: cqrshotel
      POSTGRES_PASSWORD: cqrshotel
    ports:
    - "5432:5432"
